### ISSUE TITLE
Compatibility with Blender 2.8x?

### ISSUE THREAD

**Issue by bstro** [Sprytile/Sprytile#117]
I just tried installing Sprytile to use with Blender 2.8x Beta and see the following in the addon manager:

<img width="624" alt="image" src="https://user-images.githubusercontent.com/627290/53854628-4105f880-3f98-11e9-9740-38838a98d7f7.png">

Any plans to update this addon, or should I downgrade to <2.8?

**Comment by unknowndevice** [comment]
2.8 is still in beta and not production ready, so there's currently no support for it yet. for now I would downgrade if you want to use the plugin

**Comment by bstro** [comment]
thanks!

**Comment by arvz** [comment]
2.8 is in Release Candidate stage now with the full release coming out really soon, any changes to this? Is it gonna get updated?

**Comment by unknowndevice** [comment]
@arvz there are forks that are working 2.8 support but right now the main developer doesn't have time to do this.

**Comment by hummeleBop** [comment]
Just wanted to point out that Blender 2.8 is now released.

**Comment by xan2622** [comment]
Any news regarding the Blender 2.80 compatibility ?

**Comment by unknowndevice** [comment]
There was two people working on providing a patch for support but it seems to have slowed down https://itch.io/t/409579/blender-280

Right now support will only come with the owner of the repo has time or someone submits a patch.

**Comment by ChemiKhazi** [comment]
Hi folks, thanks for being patient with this. There are a few people working on the porting effort, I'm coordinating with them on the discord now.

**Comment by dualjack** [comment]
Hello :)
Is there any possibility for stable release?

I don't know python, but if you need help with porting sprytile to Blender 2.8x, I can learn.
Thank you for your amazing work.

**Comment by skarmiglione** [comment]
please a version

**Comment by unknowndevice** [comment]
some updates on this issue https://itch.io/post/1034106

**Comment by belohlavek** [comment]
Check https://github.com/ologon/Sprytile/releases/tag/2.8-beta9

**Comment by makc** [comment]
Ok but now does it still work with 2.79b? Right?

**Comment by belohlavek** [comment]
this repo only works with 2.7x yep

**Comment by ChemiKhazi** [comment]
Closing this ticket with the official release.
https://chemikhazi.itch.io/sprytile/devlog/159431/official-blender-28-release
