### ISSUE TITLE
Tile selection UI is not shown

### ISSUE THREAD

**Issue by kkolyan** [Sprytile/Sprytile#119]
I just pressed something... I don't know. There is no tile selection popup now. Blender restart doesn't help
![image](https://sun9-19.userapi.com/c855632/v855632314/231bf6/q6woWb4HDeg.jpg)

**Comment by kkolyan** [comment]
Hm. it apprears... I have failed to google any shortcut for its hide/show. 
What am I doing wrong?

**Comment by unknowndevice** [comment]
This version of Sprytile doesn't support 2.8. You're probably using the fork here https://github.com/ologon/Sprytile

**Comment by kkolyan** [comment]
You are right... sorry :)
