### ISSUE TITLE
Error when trying to set "Floor Grid to Pixels" utilities option

### ISSUE THREAD

**Issue by larsonjj** [Sprytile/Sprytile#124]
## System Details

Blender Version: `2.83`
Blender Preferences: `Factory defaults`
Sprytile Version: `0.5.00`
OS: MacOS Catalina `10.5.5`

## Problem

Within the Sprytile options menu under Workflow > Sprytile Utilities, I try to select the "Floor Grid to Pixels" option and receive this error:

```
Traceback (most recent call last):
  File "/Users/<my_username>/Library/Application Support/Blender/2.83/scripts/addons/sprytile/sprytile_utils.py", line 1336, in invoke
    space_data.grid_scale = pixel_unit
AttributeError: 'SpaceView3D' object has no attribute 'grid_scale'

location: <unknown location>:-1
```

## Research

- Looks like `grid_scale` was removed from `Space3DView` in 2.80 (link: https://docs.blender.org/api/current/change_log.html?highlight=grid_scale).
- Possible that `grid_scale` moved to the `View3DOverlay` type (link: https://docs.blender.org/api/current/bpy.types.View3DOverlay.html?highlight=grid_scale#bpy.types.View3DOverlay.grid_scale)

**Comment by ChemiKhazi** [comment]
Thanks for the report and detailed bug reports, fixed in commit f53024c
