### ISSUE TITLE
Blender 2.8: Swap 4 & 5 Hotkeys

### ISSUE THREAD

**Issue by vulture-boy** [Sprytile/Sprytile#126]
Hello!

Just taking advantage of the hotkeys added recently and was thinking it would be more intuitive to have CCW rotation mapped to '4' and 'CW' rotation mapped to '5' (seems to be the opposite at the moment).

Rationale being numeric 'advancement' is generally associated with moving towards the right; 5 is right of 4 on most keyboards, clocks begin by advancing to the right, timelines generally are depicted advancing right (esp. in english, i'm not familiar with languages such as arabic but \o/). Also think this is more in line with other software standards.

Thanks!

**Comment by ChemiKhazi** [comment]
This is a good point, simple enough change and it makes sense. Committed in 4eddc15e667eb0ef7fd65bec39cbbe80005882ac, this will be in the next release.
