### ISSUE TITLE
Mouse issues after clicking Paint or Build

### ISSUE THREAD

**Issue by Disar** [Sprytile/Sprytile#61]
When either of the buttons are pressed and I move over any other option they all get "clicked". Can't paint/build directly either because the mouse is apparently in a different state until I focus my 3D view and click.

Blender 2.78

Edit:

I can't click any options after focusing the 3D view until i hit escape.

**Comment by ChemiKhazi** [comment]
Thanks for the report, will look into this.

**Comment by ChemiKhazi** [comment]
Hi, not sure I can replicate this bug but there's a new update to Sprytile. There were some changes to handling the UI. Can you please check if it still occurs with 0.4.0? Thanks!

**Comment by Disar** [comment]
[Here is a screen capture](https://www.youtube.com/watch?v=EjPLOwUzcvM&feature=youtu.be)

It works a bit better now, the initial state of a button press only affects the adjacent buttons/options.

Once I click in my 3D view the first click doesn't actually build/draw anything. It's only on the second click.

I'm assuming the first click actually releases the button down state on the ui button. After clicking in 3d view, When I go back to the options you notice that it doesn't automatically select any of the buttons anymore when I hover over them.

fyi, 5 days ago I did a clean image reload of my pc. Blender is clean and so is your addon.

[Perhaps it's bugged due to my mouse settings?](https://i.imgur.com/oE8MxL9.png)

I can't actually remember what the default settings were though.

**Comment by ChemiKhazi** [comment]
Thanks for this detailed bug report.

**Comment by ChemiKhazi** [comment]
Do you have any other plugins installed? Your mouse settings look to be default, so that doesn't seem to be it.

**Comment by Disar** [comment]
Nothing of significance, pie menu and ogex exporter. But as I have mentioned when I tested it I had a clean install of blender. I might have enabled something on accident, but I honestly wouldn't what that be.

im on 2.78c

**Comment by Disar** [comment]
Downloaded 2.79 and the problem is gone. No idea what it could have been.

**Comment by ChemiKhazi** [comment]
Thanks for trying it out with 2.79. Hope you have fun with using Sprytile :)

**Comment by Disar** [comment]
The problem is back. Using version 0.4.36
