### ISSUE TITLE
Tile merge errors on smaller tiles. 

### ISSUE THREAD

**Issue by hammanandre** [Sprytile/Sprytile#76]
![tilemergeerrors](https://user-images.githubusercontent.com/22626910/29049785-bb18c026-7be0-11e7-99f2-9c30a5ac8189.gif)

As shown in the gif there are some minor merge issues when building new tiles that are of stretched or flat dimensions. The new tiles in this case is half the height but the same width as the other tiles.

Resetting of the addon did not make a difference. 

If there is anymore information I could add to assist in error identification please let me know.

**Comment by ChemiKhazi** [comment]
I was aware of this error and thought I had fixed it, turns out I hadn't. Thanks for the report!
