### ISSUE TITLE
Workflow tab is empty

### ISSUE THREAD

**Issue by MasterBeany** [Sprytile/Sprytile#79]
I'm new to sprytile and I've only used blender a small amount in the past and recently got into 3d because of sprytile, but for some reason the workflow tab is empty.

I'm using sprytile 0.4.21 and I'm using blender on steam (not sure if that is the problem). I'm using Windows 10 if that's helpful. I tried searching for a solution but I can't seem to figure out why there's nothing in the workflow tab.

Thanks in advance.

**Comment by ChemiKhazi** [comment]
Thanks for reporting this issue. It looks like something is incompatible with Blender 2.79, which is the version Steam is running.

I'll look into this ASAP.

**Comment by MasterBeany** [comment]
Thank you for the quick reply, I actually just tweeted at you. Really nice pluggin by the way..

**Comment by ChemiKhazi** [comment]
If you are willing to work with a non Steam version of Blender, you can [download the zip version](http://download.blender.org/release/Blender2.78/) of Blender 2.78c for your processor (most likely 64bit but please check).

**Comment by MasterBeany** [comment]
I'll do that for now. My processor is definitely 64 bit. Thank you for the assistance!

**Comment by ChemiKhazi** [comment]
You're welcome, have fun with Sprytile!

**Comment by ChemiKhazi** [comment]
This bug is fixed. For some reason 2.79 did not include an icon that was being used with the workflow panel. This actually seems to replicate issue #30 but with an official build of Blender instead of a development build.
