### ISSUE TITLE
'modual' object has no attribute '__path__'  [what does this mean?]

### ISSUE THREAD

**Issue by foamysock** [Sprytile/Sprytile#86]
![image](https://user-images.githubusercontent.com/32686605/31408724-24c7acd8-adcf-11e7-8c44-44a146c105f9.png)

**Comment by ChemiKhazi** [comment]
It looks like you're using Blender 2.75. Sprytile is only supported from Blender 2.77 and higher.

**Comment by ChemiKhazi** [comment]
If you need to keep 2.75 for other reasons but would still like to use Sprytile my suggestion is to install a newer version of Blender using the zip file installers. I have multiple versions of Blender installed for testing purposes using zip files and it works fine for me.
