### ISSUE TITLE
Error when load a tileset

### ISSUE THREAD

**Issue by abnr** [Sprytile/Sprytile#87]
When I click on Load Tileset I got this error:

Traceback (most recent call last):
  File "/home/acr/.config/blender/2.78/scripts/addons/SpryTile/sprytile_utils.py", line 740, in execute
    SprytileLoadTileset.load_tileset_file(context, self.filepath)
  File "/home/acr/.config/blender/2.78/scripts/addons/SpryTile/sprytile_utils.py", line 747, in load_tileset_file
    texture_name = filepath[filepath.rindex('\\') + 1:]
ValueError: substring not found

location: <unknown location>:-1

location: <unknown location>:-1

**Comment by ChemiKhazi** [comment]
Thank you for this report, I'll look into this.

**Comment by abnr** [comment]
I think its related with the filepath separator, in windows it is \ in
linux it is / (I'm using blender on linux).. maybe there is some portable
way to code this in python..

**Comment by ChemiKhazi** [comment]
Could you please let me know if this works for you?

[sprytile-v0.4.24-beta.zip](https://github.com/Sprytile/Sprytile/files/1379790/sprytile-v0.4.24-beta.zip)

**Comment by abnr** [comment]
Yes, it's working. Thank you.
