### ISSUE TITLE
Increase Auto Pad Offset Limits

### ISSUE THREAD

**Issue by ChemiKhazi** [Sprytile/Sprytile#92]
Default auto pad offset settings still does not overcome Unity's default rendering weirdness, resulting in visible seams.

Default of 0.05 will show seams even up close to the geometry, 0.20 hides seams at close range but gets visible further away.

**Comment by ChemiKhazi** [comment]
The unity seams issue has been solved via renderer setting. Closing this issue.

**Comment by Ransomwave** [comment]
Hello, **is there a config file/variable/value I can change to increase this?** It seems like a pretty hard coded thing.

I'm having the same issues as you, but I am using an engine that does not allow me to change renderer settings (engine developers refuse to allow textures to be scaled in nearest neighbour), so I am left with models that have VERY noticeable seams. While a 2px offset solves this (for the most part), it is really time consuming to have to add a 2px padding to every texture I use.

Arbitrary auto pad values would be great! (sorry for necro-posting)

**Comment by Ransomwave** [comment]
> **is there a config file/variable/value I can change to increase this?**

Found how to change the maximum and minimum pad offset. Posting this here to anybody on the internet who might be looking for a way to do this:

Here are the lines of code responsible for setting the max/min variables.
https://github.com/Sprytile/Sprytile/blob/6b68d0069aef5bfed6ab40d1d5a94a3382b41619/__init__.py#L551C1-L557C6

Make sure to not crazy with the values!
