### ISSUE TITLE
Tileset images larger than 1024x1024 don't show tile selection palette

### ISSUE THREAD

**Issue by thesambassador** [Sprytile/Sprytile#93]
Open a new Blender instance
Select the Cube
Go to the Sprytile tab
Click Load Tileset
Select an image that's 2048x2048
Enter Edit Mode
Click the Build button

Actual - No tile palette shows up
Expected - Tile palette shows up

I only tested this with 2048 and 4096 for sizes.

**Comment by ChemiKhazi** [comment]
Fixed in version 0.4.35, thank you for filing the issue!
