### ISSUE TITLE
Invalid JSON generated by Sprytile

### ISSUE THREAD

**Issue by ZedCode** [Sprytile/Sprytile#96]
Hi,

When I use sprytile as a method to create an object in blender, a property gets added to the object, something along the lines of `'sprytile_mats': [<bpy id prop: owner="SCScene", name="", address=0x7fb063282628>]` -- the end result of this being that when you pass the value of `sprytile_mats` to the `json.dumps()` method, you get an error because a `[` is not valid JSON.

This came up when using the BlenderPanda exporter (here: https://github.com/Moguri/BlenderPanda/issues/36) where there is another issue open tracking how they could account for this on their side as well.

**Comment by ChemiKhazi** [comment]
I think this would be a Blender issue, sprytile_mats is being set using a Blender function, I have no control over its output.

Tangentially, it's nice to know about BlenderPanda. 🐼 3D was the first engine I programmed with! I used to be ZeroByte on the P3D forums.

**Comment by ZedCode** [comment]
Hi ChemiKhazi,

That's awesome! I'm just getting back into Panda3D after a very very long break and was hoping to put together a small group of folks to work on an open source game. Right now I'm in the phase of pioneering the toolchain for everyone to install and Sprytile is a natural fit if I can overcome this issue.

I assume this is because of https://github.com/Sprytile/Sprytile/blob/65bc236a5947f6b690052a8468e80cc290e560d2/__init__.py#L627 ?

I guess I'm forced to agree with your assessment that the problem appears to be in Blender. Bummer.

**Comment by ZedCode** [comment]
As a work around, would it be possible to update Sprytile to have a "purge from model" option that would nuke any properties set to make exporting less...finicky?

**Comment by ChemiKhazi** [comment]
A data purge sounds like a reasonable request, open a new issue for it so I don't forget.

Would be interested in the outcome of your project, my college portfolio was created with Blender and Panda3D with the same aesthetics I'm using with Sprytile. Best of luck!

**Comment by ZedCode** [comment]
Thanks! I'll come back and let you know if we build anything useful!
