### ISSUE TITLE
Feature Request - Data Purge

### ISSUE THREAD

**Issue by ZedCode** [Sprytile/Sprytile#97]
During investigation of https://github.com/Sprytile/Sprytile/issues/96 it was determined that Blender's `bpy.props.CollectionProperty` is (can?) returning the wrong thing, and therefore it would be useful to be able to purge this property via a button in the UI.

Some sort of "Sprytile" clean up feature which would leave only the mesh and UV map would be idea, but unblocking my specific issue is a great first step :)

**Comment by ZedCode** [comment]
I was hoping you could help me with a work around in the meantime. I tried opening the python console and doing:
```
bpy.types.Scene.sprytile_mats = None
```
But that appears to have no affect and still shows up with that property on the output. Any chance you can point me toward a work around in the mean time as I do not understand Python's scripting API?

**Comment by ChemiKhazi** [comment]
Oof, sorry this totally slipped my mind, I got slammed at work and haven't been able to put in work on my side projects.

**Comment by ChemiKhazi** [comment]
Version 0.4.32 has functionality to clear data from the Blender scene. Hope this helps!

![image](https://user-images.githubusercontent.com/2573643/36302855-f603b3de-1344-11e8-9a34-c7fca0ff441d.png)
